
expose_metrics: false
  
input:
  use_terminal: true
  use_rest: false
  
encode:
  codec: "h.264"
  segment_type: "fmp4"
  segment_duration: 2
  concurrent_encodings: 2
  output_ffmpeg_command: false
  
upload:
  s3:
    use: false
    s3_endpoint: ""
    s3_access_key: ""
    s3_secret_key: ""
    s3_use_ssl: true
  store_local: ""
  concurrent_uploads: 10