ingest:
  cli:
    enabled: true
  rest:
    enabled: false
    port: ":1137" # :1137

encode:
  concurrent_encodings: 2 
  output_ffmpeg_command: false
  
dispatch:
  s3:
    enabled: true
    bucket: 
    endpoint: 
    access_key: 
    secret_key: 
    use_ssl: true
  local:
    enabled: false
    store_at:


  